### ISSUE TITLE
CAN bus & IO board tracking issue

### ISSUE THREAD

**Issue by KoffeinFlummi** [tudsat-rocket/sam#34]
- [x] Implement CAN transmission in `mithril` (https://github.com/tudsat-rocket/mithril/commit/b70dab484732395f04541e608358857ecfa41d8f)
- [x] Include CAN bus message definitions in `shared_types` (#33)
  - [x] Adjust battery board firmware & mithril to use these types.
- [x] Implement transmission of ACS output messages in mithril, probably hardcode outputs for now?
- [x] Implement IO board firmware functionality
  - [x] Reception of output messages
  - [x] Handling of connection loss, failsafe behaviour
  - [x] Implement transmission of sensor messages
  - [x] Finish implementation of IO board status messages (power & temperatures)
  - [x] Finish/test payload UART/CAN bridge & telemetry downlink
  - [x] Implement wake up signals for payloads
- [x] Implement sensor message processing in mithril, think about telemetry integration (#19, hardcode IDs, implement configuration via GUI?)
